// @ts-check
// This file is regenerated by Wails during the final build.

export function AgentCredential() { return window['go']['main']['App']['AgentCredential'](); }
export function AgentOpenAITunnelInfo() { return window['go']['main']['App']['AgentOpenAITunnelInfo'](); }
export function ClearAgentOpenAITunnel() { return window['go']['main']['App']['ClearAgentOpenAITunnel'](); }
export function ClearOpenAITunnel() { return window['go']['main']['App']['ClearOpenAITunnel'](); }
export function ConfigureAgentOpenAITunnel(arg1, arg2) { return window['go']['main']['App']['ConfigureAgentOpenAITunnel'](arg1, arg2); }
export function ConfigureOpenAITunnel(arg1, arg2) { return window['go']['main']['App']['ConfigureOpenAITunnel'](arg1, arg2); }
export function ConnectionInfo() { return window['go']['main']['App']['ConnectionInfo'](); }
export function DeleteWorkspace(arg1) { return window['go']['main']['App']['DeleteWorkspace'](arg1); }
export function OpenAITunnelInfo() { return window['go']['main']['App']['OpenAITunnelInfo'](); }
export function RegenerateAgentAPIKey() { return window['go']['main']['App']['RegenerateAgentAPIKey'](); }
export function RegenerateMCPIdentities() { return window['go']['main']['App']['RegenerateMCPIdentities'](); }
export function RuntimeSnapshot() { return window['go']['main']['App']['RuntimeSnapshot'](); }
export function SetAgentEnabled(arg1) { return window['go']['main']['App']['SetAgentEnabled'](arg1); }
export function UpdateCodexAccessProfile(arg1) { return window['go']['main']['App']['UpdateCodexAccessProfile'](arg1); }
export function UpdateCodexNetworkAccess(arg1) { return window['go']['main']['App']['UpdateCodexNetworkAccess'](arg1); }

export function UpdateCodexRemoteGitRewrite(arg1) { return window['go']['main']['App']['UpdateCodexRemoteGitRewrite'](arg1); }
export function ActivateAgentTunnelProfile(arg1) { return window['go']['main']['App']['ActivateAgentTunnelProfile'](arg1); }
export function ActivateCodingTunnelProfile(arg1) { return window['go']['main']['App']['ActivateCodingTunnelProfile'](arg1); }
export function AgentTunnelProfiles() { return window['go']['main']['App']['AgentTunnelProfiles'](); }
export function CodingTunnelProfiles() { return window['go']['main']['App']['CodingTunnelProfiles'](); }
export function DeactivateAgentTunnelProfile() { return window['go']['main']['App']['DeactivateAgentTunnelProfile'](); }
export function DeactivateCodingTunnelProfile() { return window['go']['main']['App']['DeactivateCodingTunnelProfile'](); }
export function DeleteAgentTunnelProfile(arg1) { return window['go']['main']['App']['DeleteAgentTunnelProfile'](arg1); }
export function DeleteCodingTunnelProfile(arg1) { return window['go']['main']['App']['DeleteCodingTunnelProfile'](arg1); }
export function SaveAgentTunnelProfile(arg1, arg2, arg3, arg4) { return window['go']['main']['App']['SaveAgentTunnelProfile'](arg1, arg2, arg3, arg4); }
export function SaveCodingTunnelProfile(arg1, arg2, arg3, arg4) { return window['go']['main']['App']['SaveCodingTunnelProfile'](arg1, arg2, arg3, arg4); }