// This file is regenerated by Wails during the final build.
export function AgentCredential():Promise<any>;
export function AgentOpenAITunnelInfo():Promise<any>;
export function ClearAgentOpenAITunnel():Promise<any>;
export function ClearOpenAITunnel():Promise<any>;
export function ConfigureAgentOpenAITunnel(arg1:string,arg2:string):Promise<any>;
export function ConfigureOpenAITunnel(arg1:string,arg2:string):Promise<any>;
export function ConnectionInfo():Promise<any>;
export function DeleteWorkspace(arg1:string,arg2:string):Promise<any>;
export function OpenAITunnelInfo():Promise<any>;
export function OpenWorkspaceFolder(arg1:string,arg2:string):Promise<void>;
export function RegenerateAgentAPIKey():Promise<any>;
export function RegenerateMCPIdentities():Promise<any>;
export function RuntimeSnapshot():Promise<any>;
export function SetAgentEnabled(arg1:boolean):Promise<any>;
export function UpdateCodexAccessProfile(arg1:string):Promise<any>;
export function UpdateCodexNetworkAccess(arg1:boolean):Promise<any>;

export function UpdateCodexRemoteGitRewrite(arg1:boolean):Promise<any>;
